# name: CI - FastAPI Prisma

# on:
#   push:
#     branches: [main]
#   pull_request:
#     branches: [main]

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v3

#     - name: Set up Python 3.9
#       uses: actions/setup-python@v4
#       with:
#         python-version: 3.9

#     - name: Install dependencies
#       run: |
#         python -m venv env
#         source env/bin/activate
#         pip install --upgrade pip
#         pip install -r requirements.txt

#     - name: Generate Prisma client
#       run: |
#         source env/bin/activate
#         python -m prisma generate

    
















name: CI - FastAPI Prisma

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Load environment variables
      run: |
        echo "Loading .env into environment..."
        set -a
        source .env
        set +a

    - name: Install dependencies
      run: |
        python -m venv env
        source env/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate Prisma client
      run: |
        source env/bin/activate
        python -m prisma generate

    - name: Run Prisma migrations
      run: |
        source env/bin/activate
        prisma migrate deploy

    - name: Run tests
      run: |
        source env/bin/activate
        pytest tests/ --disable-warnings
